Implementation of POST /api/event/createEvent endpoint
bounswe/bounswe2022group2 pull request #209
Opened 2022-05-17 19:21 UTC by xltvy

This pull request is about the event creation operation, concerning a POST endpoint of our API called /event/createEvent. As discussed in #195 I will be implementing this POST endpoint and test my implementation using Postman.

After the implementation and testing stages are done, I will be preparing a documentation for the API regarding this POST endpoint.

2022-05-17 19:29 UTC, xltvy commented
The documentation of this POST endpoint can be viewed [here](https://documenter.getpostman.com/view/21003322/UyxkkRM1). It is created via Postman.

2022-05-18 09:25 UTC, bahricanyesil requested changes

2022-05-18 09:25 UTC, bahricanyesil commented on package.json
> +  "dependencies": {
I guess this package.json file is created mistakenly. Can you check that out and delete it if it is created unintentionally.

2022-05-18 09:25 UTC, bahricanyesil commented on practice-app/server/src/api/controllers/event/createEvent.js
> +    Object.keys(params).forEach(function (url_key) { url += "&" + url_key + "=" + params[url_key]; });
We may make it like "{ url += url_key + "=" + params[url_key] + "&"; });" to start the query parameters without "&" at the beginning.

2022-05-18 09:25 UTC, bahricanyesil commented on practice-app/server/src/api/controllers/event/createEvent.js
> +        throw new Error("Lesson does not exist.");
This error message should be changed as something like "server error".

2022-05-18 09:25 UTC, bahricanyesil commented on practice-app/server/src/api/controllers/event/createEventEndpoint.js
> +        console.log(resultMessage);
We can delete the console log lines.

2022-05-18 09:25 UTC, bahricanyesil commented on practice-app/server/src/api/controllers/event/createEventEndpoint.js
> +        if(err.message == "\"title\" length must be at least 3 characters long")
Normally, returning the status codes in the places where we detected the errors is the preferred approach. However, this is OK for now for the practical purposes. So, you can just resolve this without taking any action.

2022-05-18 12:28 UTC, xltvy commented
Thank you for your review and suggestions @bahricanyesil , that json file is indeed created mistakenly alongside the console logs for the debugging. Now, I have made some changes according to your suggestions and now it can be reviewed one last time.

2022-05-18 12:37 UTC, bahricanyesil commented
> Thank you for your review and suggestions @bahricanyesil , that json file is indeed created mistakenly alongside the console logs for the debugging. Now, I have made some changes according to your suggestions and now it can be reviewed one last time.

Thank you for the changes @xltvy. Did you check last time the query change we did? Did you try send query parameters and got the result as expected. If so, I will approve the pull request and merge it.

2022-05-18 12:44 UTC, xltvy commented
> > Thank you for your review and suggestions @bahricanyesil , that json file is indeed created mistakenly alongside the console logs for the debugging. Now, I have made some changes according to your suggestions and now it can be reviewed one last time.
> 
> Thank you for the changes @xltvy. Did you check last time the query change we did? Did you try send query parameters and got the result as expected. If so, I will approve the pull request and merge it.

Yes, it runs smoothly.

2022-05-18 12:52 UTC, bahricanyesil approved these changes

2022-05-18 12:52 UTC, merged