Dev frontend change password
bounswe/bounswe2022group2 pull request #537
Opened 2022-11-10 18:26 UTC by gokayyildiz

## Short Description

Change password screen that is accessed after the forget password screen and verification code screen
------

## What Does This PR Include?

1. new page for changing password without the backend connection
2. backend connection has not been established since necessary endpoint has not been implemented yet. 

------

Closes #(issue)

2022-11-14 12:53 UTC, xltvy requested changes
Thank you for your work. There are some minor things I would like to mention:

After submitting the form it redirects to the url with /home-page extension, instead we are using /home now. So we might change that.

Also we can use New Password instead of just Password as the first input field name. It would be conventionally better.

Besides componentizing the form for future use, these are only things that we might change. Rest is very good.

2022-11-19 12:37 UTC, gokayyildiz commented
@xltvy I updated the PR according to the changes requested, we can review again and merge this PR.

2022-11-25 12:04 UTC, xltvy commented
@gokayyildiz I have reviewed the final version. I think it is working fine, didn't see any errors. Only backend connection left for the component. When the endpoint is ready, we will implement the backend connection and done with the password change component for good. Nice work, we can merge!

2022-11-25 12:11 UTC, xltvy approved these changes

2022-11-25 18:25 UTC, merged